### ISSUE TITLE
results

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [sachin492002/musebox#1]
woowwwwwwww amazing job!but please could you make it increase unlimited results?its not fair shows just so few!!!

**Comment by KENPOKASMMA1982** [comment]
TELL ME PLEASE COULD YOU?

**Comment by sachin492002** [comment]
> TELL ME PLEASE COULD YOU?

Ok! I will fix it.

**Comment by KENPOKASMMA1982** [comment]
> > TELL ME PLEASE COULD YOU?
> 
> Ok! I will fix it.

thanks so much!I hope you will make it very soon my friend!!!
